### ISSUE TITLE
Update meetings section

### ISSUE THREAD

**Issue by pepicrft** [carambalabs/handbook#7]
Add missing standup meeting and add content to the retrospective meetings.

**Comment by sergigracia** [comment]
You mean this? https://github.com/carambalabs/studio/issues/3

**Comment by pepicrft** [comment]
No, I mean explaining in the handbook the meetings that we have and the purpose of each of them. The section is incomplete.

**Comment by sergigracia** [comment]
Yep, sorry I missunderstood this. 👍
